/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import fly from './fly'

export default function Spaceship_2(props) {
  const { nodes, materials } = useGLTF('./src/assets/radical_spaceship_2.glb')
  const spaceship_2 = useRef()
  const rotation = props.direction == "in" ? [0, -1.57, -Math.PI] : [0, 1.57, -Math.PI]

  fly(spaceship_2, props.direction)

  return (
    <group ref={spaceship_2} {...props} dispose={null} position={[props.posX, 0, props.posZ]} scale={0.01} >
      <mesh geometry={nodes.body.geometry} material={materials.body} rotation={rotation} scale={[-4.59, -2.31, -1]} />
      <mesh geometry={nodes.thrust.geometry} material={materials.thrust} rotation={rotation} scale={[-4.59, -2.31, -1]} />
      <mesh geometry={nodes.windows.geometry} material={materials.windows} rotation={rotation} scale={[-4.59, -2.31, -1]} />
      <mesh geometry={nodes.lights.geometry} material={materials.windows} rotation={rotation} scale={[-4.59, -2.31, -1]} />
      <mesh geometry={nodes.mainThrust.geometry} material={materials.thrust} rotation={rotation} scale={[-4.59, -2.31, -1]} />
    </group>
  )
}

useGLTF.preload('./src/assets/radical_spaceship_2.glb')
