/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import fly from './fly'

export default function Spaceship_1(props) {
  const { nodes, materials } = useGLTF('./src/assets/radical_spaceship_1.glb')
  const spaceship_1 = useRef()
  const rotation = props.direction == "in" ? [0, 0, 0] : [-Math.PI, 0, -Math.PI]

  fly(spaceship_1, props.direction)

  return (
    <group ref={spaceship_1} {...props} dispose={null} position={[props.posX, 0, props.posZ]} scale={0.01} >
      <mesh geometry={nodes.body.geometry} material={materials.body} position={[-3.51, 1.61, -2.01]} rotation={rotation} />
      <mesh geometry={nodes.windows.geometry} material={materials.windows} position={[-3.51, 1.61, -2.01]} rotation={rotation} />
      <mesh geometry={nodes.thrusters.geometry} material={materials.thrust} position={[-3.51, 1.61, -2.01]} rotation={rotation} />
    </group>
  )
}

useGLTF.preload('./src/assets/radical_spaceship_1.glb')