/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import spaceship3Url from './radical_spaceship_3.glb'

import fly from './fly'

export default function Spaceship_3(props) {
  const { nodes, materials } = useGLTF(spaceship3Url)
  const spaceship_3 = useRef()
  const rotation = props.direction == "in" ? [Math.PI / 2, 0, -3.14] : [Math.PI / 2, 0, 0]
  const position = props.direction == "in" ? [-0.32, 0, -5.81] : [0, 0, 0]
  const enginePosition = props.direction == "in" ? [0, 0, 0] : [-0.32, 0, -5.81]

  fly(spaceship_3, props.direction)

  return (
    <group ref={spaceship_3} {...props} dispose={null} position={[props.posX, 0, props.posZ]} scale={0.12} >
      <mesh geometry={nodes.body.geometry} material={materials.body} position={position} rotation={rotation} scale={[1, 5.13, 1]} />
      <mesh geometry={nodes.windows.geometry} material={materials.windows} position={position} rotation={rotation} scale={[1, 5.13, 1]} />
      <mesh geometry={nodes.engines.geometry} material={materials.body} position={enginePosition} rotation={rotation} scale={0.21} />
      <mesh geometry={nodes.thrust.geometry} material={materials.thrust} position={enginePosition} rotation={rotation} scale={0.21} />
    </group>
  )
}

useGLTF.preload('./src/assets/radical_spaceship_3.glb')
