/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Portal(props) {
  const { nodes, materials } = useGLTF('./src/assets/radical_portal.glb')
  return (
    <group {...props} dispose={null} scale={1} >
      <mesh geometry={nodes.portal.geometry} material={materials.megastructure} rotation={[Math.PI / 2, 0, 0]} scale={3.93} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Material} rotation={[Math.PI / 2, 0, 0]} scale={3.12} />
    </group>
  )
}

useGLTF.preload('./src/assets/radical_portal.glb')