/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Portal(props) {
  const { nodes, materials } = useGLTF('./src/assets/radical_portal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.portal.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.plane.geometry} material={nodes.plane.material} rotation={[Math.PI / 2, 0, 0]} scale={0.8} />
    </group>
  )
}

useGLTF.preload('./src/assets/radical_portal.glb')
