/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Spaceship(props) {
  const { nodes, materials } = useGLTF('./src/assets/radical_spaceship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cabine.geometry} material={materials.Material} position={[1.53, 0.27, 1.88]} rotation={[0.02, 0, 0]} scale={[0.77, 0.78, 1.31]} />
      <mesh geometry={nodes.bodyBottom.geometry} material={materials.Material} position={[1.62, 0, 0.84]} scale={[0.76, 1, 1.7]} />
      <mesh geometry={nodes.engine_left.geometry} material={materials.Material} position={[6.41, 0, -2.99]} scale={[0.53, 1, 1.66]} />
      <mesh geometry={nodes.engine_back.geometry} material={materials.Material} position={[1.62, 0, -7.57]} scale={[0.53, 1, 1.88]} />
      <mesh geometry={nodes.engine_right.geometry} material={materials.Material} position={[-3.25, 0, -2.99]} scale={[0.53, 1, 1.66]} />
      <mesh geometry={nodes.windows.geometry} material={materials.glass} position={[1.53, 0.27, 1.88]} rotation={[0.02, 0, 0]} scale={[0.77, 0.78, 1.31]} />
      <mesh geometry={nodes.engine_back_emission.geometry} material={materials.engine_emission} position={[1.62, 0, -7.57]} scale={[0.53, 1, 1.88]} />
      <mesh geometry={nodes.engine_left_emission.geometry} material={materials.engine_emission} position={[6.41, 0, -2.99]} scale={[0.53, 1, 1.66]} />
      <mesh geometry={nodes.engine_right_emission.geometry} material={materials.engine_emission} position={[-3.25, 0, -2.99]} scale={[0.53, 1, 1.66]} />
    </group>
  )
}

useGLTF.preload('./src/assets/radical_spaceship.glb')
