/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export default function Spaceship() {
  const spaceship = useRef()

  // useFrame((state, delta) => {
  //   if (spaceship.current.position.z < 1) {
  //     spaceship.current.position.z += 0.5
  //   } else {
  //     spaceship.current.position.z = -300
  //   }
  //   state.camera.position.x = spaceship.current.position.x;
  //   state.camera.position.y = spaceship.current.position.y + 5;
  //   state.camera.position.z = spaceship.current.position.z - 10;
  // })

  const { nodes, materials } = useGLTF('./src/assets/radical_spaceship.glb')
  return (
    <group ref={spaceship} dispose={null} position={[0, 0, -4]} scale={0.01}>
      <mesh geometry={nodes.cabine.geometry} material={materials.Material} position={[1.53, 0.24, 1.88]} rotation={[0.02, 0, 0]} scale={[0.77, 0.67, 1.31]} />
      <mesh geometry={nodes.bodyBottom.geometry} material={materials.Material} position={[1.62, 0.01, 0.84]} scale={[0.76, 0.86, 1.7]} />
      <mesh geometry={nodes.engine_left.geometry} material={materials.Material} position={[6.41, 0.01, -2.99]} scale={[0.53, 0.86, 1.66]} />
      <mesh geometry={nodes.engine_back.geometry} material={materials.Material} position={[1.62, 0.01, -7.57]} scale={[0.53, 0.86, 1.88]} />
      <mesh geometry={nodes.engine_right.geometry} material={materials.Material} position={[-3.25, 0.01, -2.99]} scale={[0.53, 0.86, 1.66]} />
      <mesh geometry={nodes.windows.geometry} material={materials.glass} position={[1.53, 0.24, 1.88]} rotation={[0.02, 0, 0]} scale={[0.77, 0.67, 1.31]} />
      <mesh geometry={nodes.engine_back_emission.geometry} material={materials.engine_emission} position={[1.62, 0.01, -7.57]} scale={[0.53, 0.86, 1.88]} />
      <mesh geometry={nodes.engine_left_emission.geometry} material={materials.engine_emission} position={[6.41, 0.01, -2.99]} scale={[0.53, 0.86, 1.66]} />
      <mesh geometry={nodes.engine_right_emission.geometry} material={materials.engine_emission} position={[-3.25, 0.01, -2.99]} scale={[0.53, 0.86, 1.66]} />
    </group>
  )
}

useGLTF.preload('./src/assets/radical_spaceship.glb')
